export const API_CREATE_TEST = 'http://localhost:8080/test/createTestId?';
export const API_GET_QUESTIONS = 'http://localhost:8080/getQuestionsWithParam?'
export const API_LOAD_QUESTIONS = 'http://localhost:8080/proccessFile'
export const API_TEST_RESULT = 'http://localhost:8080/testData/getTestResultData?testId=';
export const API_EDIT_FORM = 'http://localhost:8080/editMcq'
export const API_SUBMIT_QUESTION = "http://localhost:8080/testData/submitQuestion"
export const API_GET_REVISION_DATA = "http://localhost:8080/getRevisionData?";
export const API_GET_ALL_QUESTION_BY_IDS = "http://localhost:8080/getIncorrectQuestions?ids=";
export const API_GET_ALL_ANALYTICS_DATA = "http://localhost:8080/getAnalyticsData?byMonthOrMonthRange=";