package com.personalQuizApp.quizApp.enums;

public enum QuantChapters { TIME_AND_WORK, RATIO_AND_PROPORTION, PERCENTAGE, AVERAGE, MENSURATION, DOWNSTREAM_AND_UPSTREAM,
    SPEED_DISTANCE_AND_TIME, COMPOUND_AND_SIMPLE_INTEREST, PERMUTATION_AND_COMBINATION, DATA_INTERPRETATION, PROBABILITY,
    APPROXIMATION_AND_SIMPLIFICATION, QUADRATIC_EQUATIONS, INEQUALITIES, NUMBER_SERIES, STOCKS_AND_SHARES, PROFIT_AND_LOSS
}
