package com.personalQuizApp.quizApp.enums;

public enum ReasoningChapters {
    SEATING_ARRANGEMENT, PUZZLES, DIRECTION_TEST, INEQUALITIES, SYLLOGISM, BLOOD_RELATION, DATA_SUFFICIENCY, INPUT_OUTPUT, CODING_DECODING,
    ANALOGY, ALPHANUMERIC_SERIES , RANKING

    }
